name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'intel.zip'
        path: './intel'
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: intel.zip
        path: intel.zip
        overwrite: 'true'

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'Z790_gigabyte_udac.zip'
        path: './Z790_gigabyte_udac'
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Z790_gigabyte_udac.zip
        path: Z790_gigabyte_udac.zip
        overwrite: 'true'

  release:
    name: release
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: intel.zip
          path: zips
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Z790_gigabyte_udac.zip
          path: zips

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            zips/intel.zip
            zips/Z790_gigabyte_udac.zip
          tag_name: ${{ github.ref_name }}
          body: "Automated release of ${{ github.ref_name }}."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
